services:
  - type: web
    name: java-api
    runtime: docker
    rootDir: apps/api
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: ALLOWED_ORIGINS
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: DATABASE_USERNAME
        sync: false
      - key: DATABASE_PASSWORD
        sync: false
